# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('cliEnv')
env=cliEnv


cflags = ' -UCONFIG_PRINTF_RNDN -D_GNU_SOURCE -DUSE_FILE32API  -Iapp/quickjs -DCONFIG_BIGNUM' #-DCONFIG_BIGNUM for qjscalc


env.Library('quickjs', [
    'quickjs.c',
    'libregexp.c',
    'libunicode.c',
    'cutils.c',
    'quickjs-libc.c',
    'libbf.c',

],
CFLAGS='$CFLAGS '+cflags,
)


# ./qjsc -c -o /repl.c -m repl.js ./qjsc -fbignum -c -o /qjscalc.c qjscalc.js
source = []

source += [
    'qjsc.c',
]


libs = [
    'libquickjs.a',
]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype',

    '../../eggs/libwebp/',
]


env.Program('qjsc', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=libpath+env.get('LIBPATH'),
            CFLAGS='$CFLAGS '+cflags,
            )


source = []

source += [
    'qjs.c',
]

source += [
    'qjscalc.c',
    'repl.c'
]

env.Program('qjs', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CFLAGS='$CFLAGS '+cflags,
            )
